@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.configurablecane.mixin;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;