@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.configurablecane.mixin;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;