modLoader="javafml"
loaderVersion="[31,)"
#updateJSONURL="http://myurl.me/"
issueTrackerURL="https://github.com/gigaherz/ConfigurableReeds/issues"
displayURL="https://github.com/gigaherz/ConfigurableReeds"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="gigaherz"

[[mods]]
modId="configurablecane"
version="${file.jarVersion}"
displayName="Configurable Cane"
description='''
Lets you tweak the growth of sugarcane
'''

[[dependencies.configurablecane]]
   modId="forge"
   mandatory=true
   versionRange="[31.2.19,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.configurablecane]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.15.2,1.16)"
   ordering="NONE"
   side="BOTH"

