modLoader="javafml"
loaderVersion="[46,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/ConfigurableReeds/issues"

[[mods]]
   modId="configurablecane"
   version="${file.jarVersion}"
   displayName="Configurable Cane"
   description='''
Lets you tweak the growth of sugarcane
'''
   authors="gigaherz"
   #updateJSONURL="http://myurl.me/"
   displayURL="https://github.com/gigaherz/ConfigurableReeds"

[[dependencies.configurablecane]]
   modId="forge"
   mandatory=true
   versionRange="[46.0.1,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.configurablecane]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20,1.21)"
   ordering="NONE"
   side="BOTH"

