modLoader="javafml"
loaderVersion="[33,)"
license="BSD (3 clause)"

[[mods]]
   modId="configurablecane"
   version="${file.jarVersion}"
   displayName="Configurable Cane"
   description='''
Lets you tweak the growth of sugarcane
'''
   credits="Thanks for this example mod goes to Java"
   authors="gigaherz"
   #updateJSONURL="http://myurl.me/"
   displayURL="https://github.com/gigaherz/ConfigurableReeds"
   issueTrackerURL="https://github.com/gigaherz/ConfigurableReeds/issues"

[[dependencies.configurablecane]]
   modId="forge"
   mandatory=true
   versionRange="[33.0,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.configurablecane]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.2,1.17)"
   ordering="NONE"
   side="BOTH"

