modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/ConfigurableReeds/issues"

[[mods]]
   modId="configurablecane"
   version="${file.jarVersion}"
   displayName="Configurable Cane"
   description='''
Lets you tweak the growth of sugarcane and cactus
'''
   authors="gigaherz"
   #updateJSONURL="http://myurl.me/"
   displayURL="https://github.com/gigaherz/ConfigurableReeds"

[[mixins]]
config="configurablecane.mixins.json"

[[dependencies.configurablecane]]
   modId="neoforge"
   type="required"
   versionRange="[21.0.0-beta,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.configurablecane]]
   modId="minecraft"
   type="required"
   versionRange="[1.21,1.22)"
   ordering="NONE"
   side="BOTH"

