@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.configurablecane;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;